### ISSUE TITLE
Do not use uniqid for security purposes 

### ISSUE THREAD

**Issue by Thunder33345** [ImagicalGamer/ImagicalAuth#1]
http://php.net/manual/en/function.uniqid.php
"This function does not create random nor unpredictable strings. This function must not be used for security purposes. Use a cryptographically secure random function/generator and cryptographically secure hash functions to create unpredictable secure IDs."
"This function does not generate cryptographically secure tokens, in fact without being passed any additional parameters the return value is little different from microtime(). If you need to generate cryptographically secure tokens use openssl_random_pseudo_bytes()."

**Comment by ImagicalGamer** [comment]
:+1: It was changed in an update I haven't committed to the repo yet.

**Comment by Thunder33345** [comment]
okayy

**Comment by ImagicalGamer** [comment]
@Thunder33345 Any idea why this isn't making the directory?
`@mkdir($this->getDataFolder() . "/players/" . $name . ".yml");`
$name is properly defined btw

**Comment by Thunder33345** [comment]
same mine
public function logToFile($name, $text)
{
	if ($this->yml["Log"]) {
		$file = $this->getDataFolder() . "/log/" . $name . ".yml";
		$fh = fopen($file, 'a');
		$time = gmdate('Y-m-d h:i:s \G\M\T');
		fwrite($fh, $time . " " . $text . "\n");
	}
} did not work
maybe mkdir($this->getDataFolder() . "/players/", 0777,true);

**Comment by ImagicalGamer** [comment]
:+1: Works

**Comment by Thunder33345** [comment]
the mkdir works?!
cool
